---
name: Sys-Statistics-Linux
version: 0.08
author:
  - Jonny Schulz
abstract: Collect linux system statistics.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  IO::File: 0
  Test::More: 0
provides:
  Sys::Statistics::Linux:
    file: lib/Sys/Statistics/Linux.pm
    version: 0.08
  Sys::Statistics::Linux::CpuStats:
    file: lib/Sys/Statistics/Linux/CpuStats.pm
    version: 0.03
  Sys::Statistics::Linux::DiskStats:
    file: lib/Sys/Statistics/Linux/DiskStats.pm
    version: 0.03
  Sys::Statistics::Linux::DiskUsage:
    file: lib/Sys/Statistics/Linux/DiskUsage.pm
    version: 0.02
  Sys::Statistics::Linux::FileStats:
    file: lib/Sys/Statistics/Linux/FileStats.pm
    version: 0.02
  Sys::Statistics::Linux::LoadAVG:
    file: lib/Sys/Statistics/Linux/LoadAVG.pm
    version: 0.02
  Sys::Statistics::Linux::MemStats:
    file: lib/Sys/Statistics/Linux/MemStats.pm
    version: 0.04
  Sys::Statistics::Linux::NetStats:
    file: lib/Sys/Statistics/Linux/NetStats.pm
    version: 0.02
  Sys::Statistics::Linux::PgSwStats:
    file: lib/Sys/Statistics/Linux/PgSwStats.pm
    version: 0.02
  Sys::Statistics::Linux::ProcStats:
    file: lib/Sys/Statistics/Linux/ProcStats.pm
    version: 0.03
  Sys::Statistics::Linux::Processes:
    file: lib/Sys/Statistics/Linux/Processes.pm
    version: 0.02
  Sys::Statistics::Linux::SockStats:
    file: lib/Sys/Statistics/Linux/SockStats.pm
    version: 0.02
  Sys::Statistics::Linux::SysInfo:
    file: lib/Sys/Statistics/Linux/SysInfo.pm
    version: 0.02
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
