---
name: Sys-Statistics-Linux
version: 0.23
author:
  - Jonny Schulz
abstract: Front-end module to collect system statistics
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Test::More: 0
  UNIVERSAL: 0
  UNIVERSAL::require: 0
provides:
  Sys::Statistics::Linux:
    file: lib/Sys/Statistics/Linux.pm
    version: 0.23
  Sys::Statistics::Linux::Compilation:
    file: lib/Sys/Statistics/Linux/Compilation.pm
    version: 0.01
  Sys::Statistics::Linux::CpuInfo:
    file: lib/Sys/Statistics/Linux/CpuInfo.pm
    version: 0.02
  Sys::Statistics::Linux::CpuStats:
    file: lib/Sys/Statistics/Linux/CpuStats.pm
    version: 0.10
  Sys::Statistics::Linux::DiskStats:
    file: lib/Sys/Statistics/Linux/DiskStats.pm
    version: 0.14
  Sys::Statistics::Linux::DiskUsage:
    file: lib/Sys/Statistics/Linux/DiskUsage.pm
    version: 0.07
  Sys::Statistics::Linux::FileStats:
    file: lib/Sys/Statistics/Linux/FileStats.pm
    version: 0.06
  Sys::Statistics::Linux::LoadAVG:
    file: lib/Sys/Statistics/Linux/LoadAVG.pm
    version: 0.06
  Sys::Statistics::Linux::MemStats:
    file: lib/Sys/Statistics/Linux/MemStats.pm
    version: 0.10
  Sys::Statistics::Linux::NetStats:
    file: lib/Sys/Statistics/Linux/NetStats.pm
    version: 0.11
  Sys::Statistics::Linux::PgSwStats:
    file: lib/Sys/Statistics/Linux/PgSwStats.pm
    version: 0.10
  Sys::Statistics::Linux::ProcStats:
    file: lib/Sys/Statistics/Linux/ProcStats.pm
    version: 0.11
  Sys::Statistics::Linux::Processes:
    file: lib/Sys/Statistics/Linux/Processes.pm
    version: 0.12
  Sys::Statistics::Linux::SockStats:
    file: lib/Sys/Statistics/Linux/SockStats.pm
    version: 0.06
  Sys::Statistics::Linux::SysInfo:
    file: lib/Sys/Statistics/Linux/SysInfo.pm
    version: 0.06
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
